# Generated by Django 5.2.9 on 2026-03-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_teacher3_image5_alter_book_id_alter_booking1_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Address2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Email2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Password2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Phonenumber2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Username2',
        ),
        migrations.AddField(
            model_name='student',
            name='Address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Phonenumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Username',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='pending', max_length=20, null=True),
        ),
    ]
