# Generated by Django 5.2.9 on 2026-03-25 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_remove_student_address2_remove_student_email2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_as_parent', to='app.student'),
        ),
        migrations.AlterField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_as_parent', to='app.student'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_as_sender', to='app.student'),
        ),
        migrations.AlterField(
            model_name='booking1',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_as_parent', to='app.student'),
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
