# Generated by Django 5.2.9 on 2026-03-25 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_payment_parent_alter_review_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking1',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='review',
            name='parent',
        ),
    ]
